name: Python Package using Conda

on:
  push:
    branches: [ "work" ]

jobs:
  build-linux:
    runs-on: cpu

    steps:
      - uses: actions/checkout@v3
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file tests/environment_cpu.yml --name test -q
      - name: Install Stereopy dependencies
        run: |
          conda init bash
          source ~/.bashrc
          conda activate test
          pip install -r requirements.txt -q
          # TODO temporarily not install `tests/extra_requirements.txt`
          # pip install -r tests/extra_requirements.txt -q
          pip install pathlib -q
          ~/anaconda3/envs/test/bin/python setup.py develop
      - name: Test with pytest
        run: |
          ~/anaconda3/envs/test/bin/python -m pytest