name: CPU Windows PyTest in Conda

on:
  push:
    branches: [ "work" ]

jobs:
  build-linux:
    runs-on: Windows

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          conda env update --file tests/workflows/environment_win.yml --name test -q
      - name: Install Stereopy dependencies
        run: |
          conda init bash
          source ~/.bashrc
          conda activate test
          pip install -r requirements.txt -q
          pip install pathlib -q
          G:\linliang\anaconda\envs\test\python.exe setup.py develop
      - name: Test with pytest
        run: |
          G:\linliang\anaconda\envs\test\python.exe -m pytest